MEMORY
{
    /* AXI 内存 (512KB) - 0x0800_0000 ~ 0x0807_FFFF */
    RAM : ORIGIN = 0x08000000, LENGTH = 512K
}

/* 区域别名 - 默认所有段使用 RAM */
REGION_ALIAS("REGION_TEXT", RAM);
REGION_ALIAS("REGION_RODATA", RAM);
REGION_ALIAS("REGION_DATA", RAM);
REGION_ALIAS("REGION_BSS", RAM);
REGION_ALIAS("REGION_HEAP", RAM);
REGION_ALIAS("REGION_STACK", RAM);